# Generated by Django 5.0.2 on 2024-02-26 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.titles"
            ),
        ),
        migrations.AlterField(
            model_name="titles",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.reviews",
            ),
        ),
    ]
