# Generated by Django 5.0.2 on 2024-02-26 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_reviews_title_alter_titles_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(model_name="titles", name="review",),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("comment", models.CharField(max_length=200)),
                ("date_posted", models.DateField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("overview", models.CharField(max_length=1000)),
                ("img_url", models.CharField(max_length=1000)),
                (
                    "movie_or_tv",
                    models.CharField(
                        choices=[("MOVIE", "movie"), ("TV", "tv")], max_length=20
                    ),
                ),
                ("ratings", models.FloatField(default=0.0)),
                (
                    "genres",
                    models.ManyToManyField(related_name="titles", to="app.genre"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.review",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Reviews",),
        migrations.DeleteModel(name="Titles",),
    ]
