# Generated by Django 5.0.2 on 2024-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_genre_remove_titles_review_review_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="titles", to="app.genre"
            ),
        ),
    ]
