# Generated by Django 5.0.2 on 2024-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_title_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="movie_or_tv",
            field=models.CharField(
                choices=[("movie", "movie"), ("tv", "tv")], max_length=20
            ),
        ),
    ]
