# Generated by Django 5.0.2 on 2024-02-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_title_movie_or_tv"),
    ]

    operations = [
        migrations.RemoveField(model_name="title", name="review",),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="app.title",
            ),
            preserve_default=False,
        ),
    ]
