# Generated by Django 5.0.3 on 2024-03-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_review_date_posted_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="review", unique_together=set(),),
    ]
