# Generated by Django 5.0.3 on 2024-03-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review", name="date_posted", field=models.DateField(),
        ),
    ]
