# Generated by Django 5.0.3 on 2024-03-11 09:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_review_date_posted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="id",
            field=models.IntegerField(
                default=app.models.generate_unique_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
