# Generated by Django 5.0.3 on 2024-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_passwordresettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="review",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(name="PasswordResetToken",),
    ]
