# Generated by Django 5.0.3 on 2024-08-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_validationtoken_alter_review_date_posted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review", name="comment", field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="title",
            name="overview",
            field=models.TextField(max_length=1000),
        ),
    ]
